---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-planner-deployment
  namespace: default
  labels:
    app: meal-planner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meal-planner
      tier: otp 
  template:
    metadata:
      labels:
        app: meal-planner
        tier: otp 
    spec:
      containers:
        - name: meal-planner
          image: meal-planner:latest
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_STRATEGY
              value: k8s_gossip
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP
