---
apiVersion: v1
kind: Service
metadata:
  name: meal-planner-svc-headless
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app: meal-planner
    tier: otp 
